export const FETCHING_MYINFORMATION_REQUEST = '[PERSONAL] MYINFORMATION_REQUEST';
export const FETCHING_MYINFORMATION_SUCCESS = '[PERSONAL] MYINFORMATION_SUCCESS';
export const FETCHING_MYINFORMATION_FAILURE = '[PERSONAL] MYINFORMATION_FAILURE';
